##########################################################
#
# Author: Longbo Qiao
# email: longboqiao@gmail.com
# date: June 2013
#
# this script does most of the text cleaning except: remove
# punctuations and convert all strings to lowercase
# NNP analysis should use the file generated by this script
##########################################################
import json
import csv
import collections
import re
from textProc import *
from readColFromFile import *

#   this script does most of the text cleaning except: puncuation and lowercase
#   want to save it for NNP

def tweetsProc(alist,outputFile):
    CleanedTweets = open(outputPath+outputFile,'wb')
    outputCleanedTweetsWriter = csv.writer(CleanedTweets,delimiter='^')
    for tweet in alist:
        #tweets = ''
        #tweets = tweet.decode('utf-8')
        tweets = negconv(tweet)
        tweets = removeLinks(tweets)
        tweets = removeat(tweets)
        #tweets = toLowercase(tweets)
        #tweets = removePunc(tweets)
        filtered_words = []
        tweets = removestop(tweets)
        print tweets
        outputCleanedTweetsWriter.writerow([tweets])
    return cleanedTweets

cleanedTweets = []
outputList = []
data_by_csv =[]
stopword = []
filtered_words = []
outputPath =  'processed/'
inputPath = '../Data Collection/processed/'
rawTweets = 'Tweets_with_cols.txt'
outputCleanedTweets = "cleanedTweetsOnlyLess.txt"

tweetsProc(readColFromFile(inputPath,rawTweets,7),outputCleanedTweets)
